apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollout-example
  namespace: argo-rollouts
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-rollout-example
  template:
    metadata:
      labels:
        app: argo-rollout-example
    spec:
      containers:
      - name: argo-rollout-example
        image: quay.io/mcaruso/argo-rollout-example:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
