apiVersion: v1
kind: Service
metadata:
  name: argo-rollout-example
  namespace: argo-rollouts
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: argo-rollout-example
