apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-example-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/pacaruso/argo-rollout.git'
    path: helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
